/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ykyang' at '12/6/16 7:16 PM' with Gradle 3.2.1
 *
 * @author ykyang, @date 12/6/16 7:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
