/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ykyang' at '11/8/16 4:19 PM' with Gradle 3.1
 *
 * @author ykyang, @date 11/8/16 4:19 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
