/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.allnix.classic;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.allnix.classic.App;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
