/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ykyang' at '12/15/16 3:03 PM' with Gradle 3.2.1
 *
 * @author ykyang, @date 12/15/16 3:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
