/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ykyang' at '11/23/16 10:19 AM' with Gradle 3.1
 *
 * @author ykyang, @date 11/23/16 10:19 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
