CREATE TABLE IF NOT EXISTS JobInput (
  ID	CHAR(36)	PRIMARY KEY,
  JSON	TEXT		NOT NULL
);
# Single line version
# CREATE TABLE IF NOT EXISTS JobInput (Id CHAR(36) PRIMARY KEY, Jon TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS Job (
  ID	CHAR(36)	PRIMARY KEY,
  JSON	TEXT		NOT NULL
);
# Single line version
# CREATE TABLE IF NOT EXISTS Job (Id CHAR(36) PRIMARY KEY, Json TEXT NOT NULL);